apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-web-tls
  namespace: hello
spec:
  secretName: hello-web-tls
  issuerRef:
    name: letsencrypt-staging   # change to letsencrypt-prod after it works
    kind: ClusterIssuer
  dnsNames:
    - test.1f100.dev
